workers=50
interval = 300

[db]
host="10.10.10.10"
user="AIS_RPC"
password="123123123123123"
sid="10.10.10.240/dbsid"
switch_root_id=201
alive_param_id=51820501
workers=50

[default]
name="default"
minport=1
maxport=28
community="public"
snmp_offset=0
[default.oids]
Output=".1.3.6.1.2.1.31.1.1.1.10"
Input=".1.3.6.1.2.1.31.1.1.1.6"
crc="1.3.6.1.2.1.10.7.2.1.3"
brd=".1.3.6.1.2.1.31.1.1.1.9"

[carbon]
hosts = [
	"127.0.0.1:2003",
	"127.0.0.1:2103",
	"127.0.0.1:2203",
	"127.0.0.1:2303"
]

[[models]]
name="MES2124F"
maxport=24
snmp_offset=48

[[models]]
name="DES-1228/ME"

[[models]]
name="DES-1210-28/ME"

[[models]]
name="DES-3200-26"
maxport=26

[[models]]
name="DES-3010G"
maxport=10

[[models]]
name="DES-3200-10"
maxport=10

[[models]]
name="DGS-3200-10"
maxport=10

[[models]]
name="DGS-3612G"
maxport=12

[[models]]
name="DES-3200-10_rev_C1"
maxport=10

[[models]]
name="DES-3200-18"
maxport=18

[[models]]
name="DES-3200-18_rev_C1"

[[models]]
name="DES-3200-26_rev_C1"
maxport=26

[[models]]
name="DES-3200-28"

[[models]]
name="DES-3200-28_rev_C1"

[[models]]
name="DES-3200-28F"

[[models]]
name="DES-3200-28F_rev_C1"

[[models]]
name="DES-3028"

[[models]]
name="DES-3052"
maxport=52

[[models]]
name="DES-3052P"
maxport=52

[[models]]
name="DES-3200-52_rev_C1"
maxport=52

[[models]]
name="DES-3028G"

[[models]]
name="DES-3028P"

[[models]]
name="DGS-3100-24TG"
maxport=24

[[models]]
name="DGS-3120-24Sc"
maxport=24

[[models]]
name="DGS-3120-24Tc"
maxport=24

[[models]]
name="DGS-3120-10"
maxport=10

[[models]]
name="DGS-3420-26SC"
maxport=26

[[models]]
name="DGS-3420-28SC"
maxport=28

[[models]]
name="DGS-3627G"
maxport=26

[[models]]
name="DXS-3326GSR"
maxport=24

[[models]]
name="DES-3526"
maxport=26

[[models]]
name="DES-3526_DC"
maxport=26

[[models]]
name="DGS-3650"
maxport=50

[[models]]
name="DXS-3350SR"
maxport=50
